### ISSUE TITLE
thanks, works well!!

### ISSUE THREAD

**Issue by Ruchechnik** [S-o-T/telegram-3proxy-install#1]
please tell me how to create another user ?

**Comment by S-o-T** [comment]
You need to put the credentials of new user inside of /usr/local/etc/3proxy/userpass (format is "$USERNAME:CL:$PASS") and insert the rule for your new user into /usr/local/etc/3proxy/3proxy.cfg (after line #23, format is "allow USERNAME *  LIST_OF_TARGET_IP'S". But why do you need the new user?

**Comment by Ruchechnik** [comment]
Thanks for your help. I want to give my friends access from my proxy. Or it is possible to distribute the same login/password to all ?

**Comment by S-o-T** [comment]
Technically, it is normal to use the same login / password for multiple clients. For this particular scenario of using a proxy server (allowing traffic only to telegram servers), I do not see any problems using the same credentials for several users. Unless you want to collect any statistics or you fear that the server will face unnecessary incoming traffic after the credentials are leaked to the public.
